version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Build preparation started
      - chmod +x ./mvnw
      - java -version
  build:
    commands:
      - echo Build started on `date`
      - echo Building the application...
      - ./mvnw clean package -DskipTests
      - echo Build completed successfully
      - ls -la target/
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'