version: 0.2

phases:
  pre_build:
    commands:
      - echo Build preparation started
      - chmod +x ./mvnw
  build:
    commands:
      - echo Build started on `date`
      - echo Building the application...
      - ./mvnw clean package -DskipTests
      - echo Build completed successfully
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/*.jar