version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build started on `date`
      - echo Creating a simple successful build
      - mkdir -p target
      - echo "Build completed successfully" > target/build-success.txt
      - echo Build completed successfully
artifacts:
  files:
    - '**/*'