version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo Skipping ECR login for now
  build:
    commands:
      - echo Build started on `date`
      - echo Building the application...
      - ./mvnw clean package -DskipTests
      - echo Build completed successfully
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Skipping Docker operations for now
artifacts:
  files:
    - target/*.jar